---
title: 手写Promise
order: 18
category:
  - 面试
  - JS
---

### 参考链接

[手写 Promise](https://zhuanlan.zhihu.com/p/183801144)

### 基础版 Promise

todo:

- 构建 Promise 对象时，需要传入一个 executor 函数，Promise 的主要业务流程都在 executor 函数中执行
- promise 有三个状态：pending，fulfilled，or reject
- executor 函数接受两个函数 resolve 和 reject，如果运行在 excutor 函数中的业务执行成功了，会调用 resolve 函数；如果执行失败了，则调用 reject 函数
- Promise 的状态不可逆，同时调用 resolve 函数和 reject 函数，默认会采取第一次调用的结果

```js
const PENDING = Symbol("PENDING"),
  FULFILLED = Symbol("FULFILLED"),
  REJECTED = Symbol("FREJECTED");

class Promise {
  constructor(executor) {
    //默认状态
    this.status = PENDING;
    //存放成功状态的值，默认为 undefined
    this.value = undefined;
    //存放失败状态的值，默认为 undefined
    this.reason = undefined;
    let resolve = (val) => {
      // 状态为 PENDING 时才可以更新状态，防止 executor 中调用了两次 resovle/reject 方法
      if (this.status === PENDING) {
        this.status = FULFILLED;
        this.value = val;
      }
    };
    let reject = (reason) => {
      if (this.status === PENDING) {
        this.status = REJECTED;
        this.reason = reason;
      }
    };
    try {
      // 立即执行，将 resolve 和 reject 函数传给使用者
      executor(resolve, reject);
    } catch (err) {
      // 发生失败时执行失败逻辑
      reject(err);
    }
  }
  // 包含一个 then 方法，并接收两个参数 onFulfilled、onRejected分别用于成功时执行和失败时执行
  then(onFulfilled, onRejected) {
    if (this.status === FULFILLED) {
      onFulfilled(this.value);
    }

    if (this.status === REJECTED) {
      onRejected(this.reason);
    }
  }
}

const promise = new Promise((resolve, reject) => {
  reject("失败");
}).then(
  (data) => {
    console.log("success", data);
  },
  (err) => {
    console.log("faild", err);
  }
);
```

但是存在一个问题，传入的 executor 可以是一个异步函数，如下所示

```js
const promise = new Promise((resolve, reject) => {
  // 传入一个异步操作
  setTimeout(() => {
    resolve("成功");
  }, 1000);
}).then(
  (data) => {
    console.log("success", data);
  },
  (err) => {
    console.log("faild", err);
  }
);

// 结果：无返回
```

由于 then 方法调用的时候，默认状态仍然为 pending 因此没有任何的返回

因此：如果在执行 then 方法时，状态仍然为 pending，那么就将成功的回调和失败的回调先保存起来，得到异步函数执行到 resolve 或时 reject 的时候，再触发这些回调

```js
const PENDING = Symbol("PENDING"),
  FULFILLED = Symbol("FULFILLED"),
  REJECTED = Symbol("FREJECTED");

class Promise {
  constructor(executor) {
    //默认状态
    this.status = PENDING;
    //存放成功状态的值，默认为 undefined
    this.value = undefined;
    //存放失败状态的值，默认为 undefined
    this.reason = undefined;

    // 存放成功的回调
    this.onResolvedCallbacks = [];
    // 存放失败的回调
    this.onRejectedCallbacks = [];

    let resolve = (val) => {
      // 状态为 PENDING 时才可以更新状态，防止 executor 中调用了两次 resovle/reject 方法
      if (this.status === PENDING) {
        this.status = FULFILLED;
        this.value = val;
        this.onResolvedCallbacks.forEach((fn) => {
          fn();
        });
      }
    };
    let reject = (reason) => {
      if (this.status === PENDING) {
        this.status = REJECTED;
        this.reason = reason;
        this.onRejectedCallbacks.forEach((fn) => {
          fn();
        });
      }
    };
    try {
      // 立即执行，将 resolve 和 reject 函数传给使用者
      executor(resolve, reject);
    } catch (err) {
      // 发生失败时执行失败逻辑
      reject(err);
    }
  }
  // 包含一个 then 方法，并接收两个参数 onFulfilled、onRejected分别用于成功时执行和失败时执行
  then(onFulfilled, onRejected) {
    if (this.status === PENDING) {
      // 如果promise的状态是 pending，需要将 onFulfilled 和 onRejected 函数存放起来，等待状态确定后，再依次将对应的函数执行
      this.onResolvedCallbacks.push(() => {
        const res = onFulfilled(this.value);
        return new Promise((resolve, reject) => {
          resolve(res);
        });
      });

      // 如果promise的状态是 pending，需要将 onFulfilled 和 onRejected 函数存放起来，等待状态确定后，再依次将对应的函数执行
      this.onRejectedCallbacks.push(() => {
        onRejected(this.reason);
      });
    }
    if (this.status === FULFILLED) {
      onFulfilled(this.value);
    }

    if (this.status === REJECTED) {
      onRejected(this.reason);
    }
  }
}
```

测试实例(一个 promise 可以多次 then)

```js
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject(100);
  }, 1000);
});

promise.then(
  () => {},
  (val) => {
    console.log(100 * 1);
  }
);

promise.then(
  () => {},
  (val) => {
    console.log(100 * 2);
  }
);

promise.then(
  () => {},
  (val) => {
    console.log(100 * 3);
  }
);
```

then 的链式调用&值穿透:promise 的优势在于可以链式调用,在我们使用 Promise 的时候，当 then 函数中 return 了一个值，不管是什么值，我们都能在下一个 then 中获取到，这就是所谓的 then 的链式调用

而且，当我们不在 then 中放入参数，例：promise.then().then()，那么其后面的 then 依旧可以得到之前 then 返回的值，这就是所谓的值的穿透

解决方法：如果每次调用 then 的时候，我们都重新创建一个 promise 对象，并把上一个 then 的返回结果传给这个新的 promise 的 then 方法

难点：上一个 then 的返回结果是一个 promise,那么会等这个 promise 执行完，promise 如果成功，就走下一个 then 的成功。可能存在 Promise 中还有 promise 的情况

解决方案：递归解析的过程（因为可能 promise 中还有 promise）

注意：原生的 Promise 是 V8 引擎提供的微任务，由于无法还原 V8 引擎的实现，所以这里使用 setTimeout 模拟异步，所以原生的是微任务，这里是宏任务

```js
const PENDING = Symbol("PENDING"),
  FULFILLED = Symbol("FULFILLED"),
  REJECTED = Symbol("FREJECTED");

const resolvePromise = (promise2, x, resolve, reject) => {
  // 自己等待自己完成是错误的实现，用一个类型错误，结束掉 promise
  if (promise2 === x) {
    return reject(
      new TypeError("Chaining cycle detected for promise #<Promise>")
    );
  }
  // 只能调用一次
  let called;
  // 后续的条件要严格判断 保证代码能和别的库一起使用
  // 先判断是否是函数，不是的话直接resolve
  if ((typeof x === "object" && x != null) || typeof x === "function") {
    try {
      // 为了判断 resolve 过的就不用再 reject 了（比如 reject 和 resolve 同时调用的时候)
      let then = x.then;
      if (typeof then === "function") {
        // 不要写成 x.then，直接 then.call 就可以了 因为 x.then 会再次取值
        then.call(
          x,
          // y是x的resolve传递进来的指
          (y) => {
            // 根据 promise 的状态决定是成功还是失败
            if (called) return;
            called = true;
            // 递归解析的过程（因为可能 promise 中还有 promise）
            resolvePromise(promise2, y, resolve, reject);
          },
          (r) => {
            // 只要失败就失败
            if (called) return;
            called = true;
            reject(r);
          }
        );
      } else {
        // 如果 x.then 是个普通值就直接返回 resolve 作为结果
        resolve(x);
      }
    } catch (e) {
      if (called) return;
      called = true;
      reject(e);
    }
  }
  // 如果 x 是个普通值就直接返回 resolve 作为结果
  else {
    resolve(x);
  }
};

class Promise {
  constructor(executor) {
    //默认状态
    this.status = PENDING;
    //存放成功状态的值，默认为 undefined
    this.value = undefined;
    //存放失败状态的值，默认为 undefined
    this.reason = undefined;

    // 存放成功的回调
    this.onResolvedCallbacks = [];
    // 存放失败的回调
    this.onRejectedCallbacks = [];

    let resolve = (val) => {
      // 状态为 PENDING 时才可以更新状态，防止 executor 中调用了两次 resovle/reject 方法
      if (this.status === PENDING) {
        this.status = FULFILLED;
        this.value = val;
        this.onResolvedCallbacks.forEach((fn) => {
          fn();
        });
      }
    };
    let reject = (reason) => {
      if (this.status === PENDING) {
        this.status = REJECTED;
        this.reason = reason;
        this.onRejectedCallbacks.forEach((fn) => {
          fn();
        });
      }
    };
    try {
      // 立即执行，将 resolve 和 reject 函数传给使用者
      executor(resolve, reject);
    } catch (err) {
      // 发生失败时执行失败逻辑
      reject(err);
    }
  }

  then(onFulfilled, onRejected) {
    // then可以不传值，如果没传值，就直接返回resolve的结果
    onFulfilled = typeof onFulfilled === "function" ? onFulfilled : (v) => v;
    //因为错误的值要让后面访问到，所以这里也要跑出个错误，不然会在之后 then 的 resolve 中捕获
    onRejected =
      typeof onRejected === "function"
        ? onRejected
        : (err) => {
            throw err;
          };
    // 在promise2的主体中执行onFulfilled, onRejected
    let promise2 = new Promise((resolve, reject) => {
      if (this.status === FULFILLED) {
        try {
          // 注：promise.then是个微任务，这里仅用setTimeout简单代替下
          setTimeout(() => {
            // 拿到onFulfilled执行的结果
            let x = onFulfilled(this.value);
            // 因为x可能是个promise，需要通过resolvePromise判断，不能直接resolve
            resolvePromise(promise2, x, resolve, reject);
          }, 0);
        } catch {
          reject(e);
        }
      }

      if (this.status === REJECTED) {
        setTimeout(() => {
          try {
            let x = onRejected(this.reason);
            resolvePromise(promise2, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        }, 0);
      }
      if (this.status === PENDING) {
        this.onResolvedCallbacks.push(() => {
          setTimeout(() => {
            try {
              let x = onFulfilled(this.value);
              resolvePromise(promise2, x, resolve, reject);
            } catch (e) {
              reject(e);
            }
          }, 0);
        });

        this.onRejectedCallbacks.push(() => {
          setTimeout(() => {
            try {
              let x = onRejected(this.reason);
              resolvePromise(promise2, x, resolve, reject);
            } catch (e) {
              reject(e);
            }
          }, 0);
        });
      }
    });
    return promise2;
  }
}
```

Promise APi 的实现

1. Promise.prototype.finally()

目标：无论如何都会执行的,且 finally() 调用通常是透明的，不会更改原始 promise 的状态，它的返回 Promise 会采用上一次的结果

比如

```js
Promise.resolve(2).finally(() => 77) 返回一个最终兑现为值 2 的 promise
```

```js
Promise.prototype.finally = function (callback) {
  return this.then(
    (value) => {
      return (
        Promise
          // 执行callback
          .resolve(callback())
          // 采用上一次的value
          .then(() => value)
      );
    },
    (reason) => {
      return (
        Promise
          // 执行callback
          .resolve(callback())
          // 采用上一次的reason
          .then(() => {
            throw reason;
          })
      );
    }
  );
};
```

2. Promise.all()

目标：接收一个 Promise[]，返回一个 Promise 实例，如果 Promise 队列中所有的实例状态都是 fulfilled，那么 Promise.all()返回的实例的状态就会变为 fulfilled，并且 resolve()的参数是一个数组，按照顺序放置队列中每个 Promise 成功后的结果，只要队列中有一个实例的状态是 rejected，那么该实例的状态也会变为 rejected

```js
const PromiseAll = function (values) {
  if (!Array.isArray(values)) {
    const type = typeof values;
    return new TypeError(`TypeError: ${type} ${values} is not iterable`);
  }
  return new Promise((resolve, reject) => {
    let resultArr = [];
    let count = 0;
    const processResultByKey = (value, index) => {
      resultArr[index] = value;
      count++;
      if (count === values.length) {
        resolve(resultArr);
      }
    };
    for (let i = 0; i < values.length; i++) {
      let value = values[i];
      if (value && typeof value.then === "function") {
        value.then(
          (value) => {
            processResultByKey(value, i);
          },
          (reason) => {
            reject(reason);
          }
        );
      } else {
        // 如果数组中是个普通类型，比如[1,2,3] 就直接放入
        processResultByKey(value, i);
      }
    }
  });
};
```

3. Promise.allSettled()

```js
Promise.allSettled = function (promises) {
  return new Promise((resolve) => {
    const results = [];
    let completed = 0;

    const processData = (index, status, value) => {
      results[index] = { status, value };
      completed++;

      if (completed === promises.length) {
        resolve(results);
      }
    };

    promises.forEach((promise, index) => {
      Promise.resolve(promise)
        .then((value) => {
          processData(index, "fulfilled", value);
        })
        .catch((reason) => {
          processData(index, "rejected", reason);
        });
    });
  });
};
```

4. Promise.race()

Promise.race()同样接收一个 Promise 队列，返回一个 Promise 实例。该方法会对队列任务完成情况进行监听，如果某一个任务最先完成 fulfilled/rejected，那么返回的实例的状态也会变成对应的 fulfilled/rejected，同时获取到最先完成的结果

```js
static race (promises) {
  return new Promise((resolve, reject) => {
    // 一起执行就是for循环
    for (let i = 0; i < promises.length; i++) {
      let val = promises[i];
      if (val && typeof val.then === "function") {
        val.then(
          (res) => {
            resolve(res);
          },
          (reason) => {
            reject(reason);
          }
        );
      } else {
        // 普通值
        resolve(val);
      }
    }
  });
};
```
